### ISSUE TITLE
Perhaps you should add some example data to make your script easier to understand and use?

### ISSUE THREAD

**Issue by endrebak** [ilarsf/gwasTools#1]
If you included the file `ExampleGWAS.txt` in the repository it would be much easier for others to understand how to use the tool. I cannot see that the format of the input file is described anywhere.

Thanks for making the code available btw, I really appreciate it 👍

**Comment by ilarsf** [comment]
Thanks. That's a good point. I just added the required input columns to the "help" information:
`Rscript ManhattanPlot.r --help`
