### ISSUE TITLE
ManhattanPlot.R: NCBI annotation not available

### ISSUE THREAD

**Issue by LisanneVijfhuizen** [ilarsf/gwasTools#3]
Hi,

For a collaboration project, we need to make Manhattan plots from our GWAS data. I have been able to use the Rscript ManhattanPlot.r and that given the following message. 

Please run the following code line by line in an interactive R session:
library(Map2NCBI)
library(data.table)
file.genelist37 <- path.expand("~/GeneList_Homo_sapiens_BUILD.37.3.txt")
genelist37 <- GetGeneList_v11("Homo sapiens",build="BUILD.37.3",savefiles=F,destfile=tempfile())
fwrite(genelist37,file.genelist37,sep="\t",quote=T)

Unfortunately, the ftp://ftp.ncbi.nih.gov/genomes/MapView for build37 is not available. Do you have other options for the annotation? 

Your help will be much appreciated.

**Comment by ilarsf** [comment]
Hi Lisanne,

I updated the Rscript and got rid off the "GetGeneList_v11" function. Annotations are now based on the UCSC NCBI RefSeq genes (excluding predicted transcripts XM* and XR*).
You should be able to select hg18, hg19, or hg38.
Please let me know if this works for you.

Thanks,
Lars
