### ISSUE TITLE
Error including candidate regions file in updated Manhattan plot script

### ISSUE THREAD

**Issue by sboer** [ilarsf/gwasTools#5]
I have successfully included a hitregions file in an older version of the Manhattan plot, but in the newest version i get an error message: 

```
Error in merge.data.table(plotdata[, .(CHROM, POS, x, y)], candidateRegions,  : 
 Elements listed in `by` must be valid column names in x and y
Calls: ManhattanPlot -> merge -> merge.data.table
```

This is the tabseparated candidate region file (I tried to change the last column name from LEGENDTEXT to LABEL, as indicated in the --help function), but nothing changed

CHROM   START   END     COL     LABEL
8       65984044        66384044        green   Novel_locus
7       20490738        20890738        green   Novel_locus
12      22975219        24975219        blue    Known_locus
8       129718772       131718772       blue    Known_locus
18      49379032        51379032        blue    Known_locus

This is the code I am running

``` 
Rscript ManhattanPlot.r --input plots/low_back_pain_H23_forplots.txt --prefix test --chr CHR --pos POS --pvalue p.value --hitregion hitregions.txt --maintitle 'test'
``` 

I might have missed an update on how to make the hitregion file, but the only difference I could see by comparing the two scripts, is the header of the last column (LEGENDTEXT vs. LABEL). The excact same code and files (except for changing the header of the last column) works when running the older script. It also works fine when dropping the --hitregion option. 

Sorry if I have missed something obvious. 

Thanks,
Sigrid

**Comment by ilarsf** [comment]
Hi Sigrid,

You were doing everything right, but I broke this function with a previous update and now fixed it with a few lines of extra code. Please download the new version and try again.

Thanks,
Lars

**Comment by sboer** [comment]
Great, thanks alot. It seems to work now :)
Sigrid
